### ISSUE TITLE
Sizes do not match

### ISSUE THREAD

**Issue by wjw1993** [dasguptar/treelstm.pytorch#11]
When I run 
`python main.py ` 
I met the following error message

> Namespace(batchsize=25, cuda=True, data='data/sick/', epochs=15, expname='test', 
>glove='data/glove/', hidden_dim=50, input_dim=150, lr=0.01, mem_dim=75, num_classes=5, >optim='adagrad', save='checkpoints/', seed=123, sparse=False, wd=0.0001)
>==> SICK vocabulary size : 2412
>==> Size of train data   : 4500
>==> Size of dev data     : 500
>==> Size of test data    : 4927
>Traceback (most recent call last):
> File "main.py", line 157, in <module>
>    main()
>  File "main.py", line 126, in main
>model.childsumtreelstm.emb.state_dict()['weight'].copy_(emb)

> RuntimeError: sizes do not match at /py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/THCTensorCopy.cu:31

The platform is Arch Linux and CUDA8.0

I would appreciate it for any reply.

**Comment by dasguptar** [comment]
Hi @wjw1993 , sorry for the delayed response, I was on leave.

Based on your error, it seems that there is some mismatch between the sizes of `model.childsumtreelstm.emb.weight` and `emb`.

Can you perhaps print the sizes of both of these right before the line giving the error, and show me what sizes you are getting?

**Comment by lastdawnsu** [comment]
I also get the same error ! When I debug, I find the error happend while the tree.num_children larger than 2. But I'm not very sure, I just fount it.

**Comment by lastdawnsu** [comment]
@dasguptar I've got how the error happended! The ChildSumTreeLSTM.get_child_states(self, tree) had some problem.
in `child_c[idx], child_h[idx] = tree.children[idx].state`
child_c[idx] and child_h[idx] should be 1*150, but
tree.children[idx].state[0] and tree.children[idx].state[1] may be 2*1*150.
Then the error happened.

**Comment by wjw1993** [comment]
@dasguptar  Thank you for your reply.  I am just a beginner of pytorch. It seems after installing conda and reset up environment, I  can't reproduce this mistake again. But thank you again.
