### ISSUE TITLE
Upgrade to pytorch 0.2

### ISSUE THREAD

**Issue by federicoFerri** [dasguptar/treelstm.pytorch#12]
When is the upgrade to pytorch 0.2 planned? (#9) Thanks @dasguptar for the amazing work done

**Comment by wq343580510** [comment]
where to download pytorch 0.12 ? the new version of pytorch is 0.2. I don't see any old version in the home page of pytorch. so I meet some problem when using the code.

**Comment by federicoFerri** [comment]
@wq343580510 you can build it from [source](https://github.com/pytorch/pytorch/releases) or use those links:
[linux python 2.7 cuda 8.0](http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp27-none-linux_x86_64.whl)
[linux python 2.7 cuda 7.5 / no cuda](http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp27-none-linux_x86_64.whl)
[linux python 3.6 cuda 8.0](http://download.pytorch.org/whl/cu80/torch-0.1.12.post2-cp36-cp36m-linux_x86_64.whl)
[linux python 3.6 cuda 7.5 / no cuda](http://download.pytorch.org/whl/cu75/torch-0.1.12.post2-cp36-cp36m-linux_x86_64.whl)
[macosx python 2.7](http://download.pytorch.org/whl/torch-0.1.12.post2-cp27-none-macosx_10_7_x86_64.whl)
[macosx python 3.6](http://download.pytorch.org/whl/torch-0.1.12.post2-cp36-cp36m-macosx_10_7_x86_64.whl)

**Comment by wq343580510** [comment]
thanks very much。 @federicoFerri

**Comment by dasguptar** [comment]
@federicoFerri @wq343580510 the codebase is now updated to support PyTorch 0.2.0

Apologies for the delay in getting around to this, I was busy with some other work, and forgot to push!

**Comment by federicoFerri** [comment]
Thanks!
