### ISSUE TITLE
No such file or directory: data/sick/train/a.toks 

### ISSUE THREAD

**Issue by adrianhust** [dasguptar/treelstm.pytorch#2]
Hi:
I need help!
IOError: [Errno 2] No such file or directory: 'data/sick/train/a.toks'
run python main.py with default paras, then throw this error.

Where this file a.toks comes from?

**Comment by dasguptar** [comment]
@adrianhust I think I forgot to mention the preprocessing needed. Basically, you need to run `./fetch_and_preprocess.sh` first, which will download the data and preprocess it.

**Comment by adrianhust** [comment]
Thank you very much!! @dasguptar 
I found it was caused by "javac -cp $CLASSPATH lib/*.java" fail. Sorry for my not being familiar with stanford corenlp tool, stanford parser and tagger need to be installed ? or just download  "stanford-postagger-2015-01-29.zip" and "stanford-parser-full-2015-01-29.zip".

**Comment by dasguptar** [comment]
@adrianhust the `fetch_and_preprocess.sh` script will first call `scripts/download.py`, which in turn downloads the Stanford Parser, Stanford Tagger, GLOVE vectors, and the SICK dataset. Could you take a look at [these lines](https://github.com/dasguptar/treelstm.pytorch/blob/master/scripts/download.py#L117-L128) to see how these things are downloaded and stored?

**Comment by adrianhust** [comment]
@dasguptar  
scripts/download.py works well, and all files required good
I tried this to fix it.
download "stanford-corenlp-full-2016-10-31.zip" and add  stanford-  corenlp-3.7.0.jar into CLASSPATH  
`CLASSPATH="lib:lib/stanford-parser/stanford-parser.jar:lib/stanford-parser/stanford-parser-3.5.1-models.jar:lib/stanford-parser/stanford-  corenlp-3.7.0.jar"`

 then 
`javac -cp $CLASSPATH lib/*/*.java`

run without errors

but in  treelstm.pytorch/scripts/preprocess-sick.py
`cmd = ('java -cp %s ConstituencyParse -tokpath %s -parentpath %s %s < %s'
         % (cp, tokpath, parentpath, tokenize_flag, filepath))
  os.system(cmd)`
throw an error 
> 错误: 找不到或无法加载主类 DependencyParse
means it cannot find or load main class DependencyParse 
I still cannot locate where DependencyParse is

**Comment by dasguptar** [comment]
@adrianhust 
Hmm, I don't know what is causing that error. As I mentioned before, this part of the code was taken from the original implementation. The DependencyParse class/function is inside the `*.jar` files, and I do not know if it can be extracted for inspection. Can you put the whole stacktrace in a Gist, and link to it?

**Comment by adrianhust** [comment]
<script src="https://gist.github.com/adrianhust/37e026cd26e1b734d4c6871ce39c7dc5.js"></script>

**Comment by dasguptar** [comment]
Closing due to lack of response.

**Comment by lawlietAi** [comment]
@adrianhust Have you solve this problem? The cause of this problem is classpath error. and I cannot modify classpath to let the code work. Is there any solution?
