### ISSUE TITLE
can not find packages

### ISSUE THREAD

**Issue by venusafroid** [dasguptar/treelstm.pytorch#36]
lib\CollapseUnaryTransformer.java:3: 错误: 程序包edu.stanford.nlp.ling不存在
import edu.stanford.nlp.ling.Label;
                            ^
lib\CollapseUnaryTransformer.java:4: 错误: 程序包edu.stanford.nlp.trees不存在
import edu.stanford.nlp.trees.Tree;
                             ^
lib\CollapseUnaryTransformer.java:5: 错误: 程序包edu.stanford.nlp.trees不存在
import edu.stanford.nlp.trees.TreeTransformer;
                             ^
lib\CollapseUnaryTransformer.java:6: 错误: 程序包edu.stanford.nlp.util不存在
import edu.stanford.nlp.util.Generics;

...
What can I do ??

**Comment by venusafroid** [comment]
I have solved the problem.

**Comment by MakiseCrissy** [comment]
Could you plz tell me how you solved this problem? thx
