### ISSUE TITLE
ChildSumTreeLSTM : fx and fh linear layer are declare but is not used

### ISSUE THREAD

**Issue by ttpro1995** [dasguptar/treelstm.pytorch#4]
Line 21, 22
```
self.fx = nn.Linear(self.in_dim,self.mem_dim)
self.fh = nn.Linear(self.mem_dim,self.mem_dim)
```
But it is never use

I think you intend to use in line 38, 39.
(perhaps typo ix with fx )
```
fx = F.torch.unsqueeze(self.ix(inputs),1)
f = F.torch.cat([self.ih(child_hi)+fx for child_hi in child_h], 0)

```

**Comment by dasguptar** [comment]
Whoa! Good catch @ttpro1995 
So it seems I was a complete klutz, and declared `fx, fh` but used `ix, ih` instead. Thanks for spotting it! Let me run the model with the fix and as soon as that is done I will merge your PR as well

**Comment by dasguptar** [comment]
@ttpro1995 Closing this issue for now, because I merged the PR. Let me know if you find any other bugs!
